name: Generate and Update Client

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.9"
        
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
          
    - name: Download latest OpenAPI spec
      run: |
        curl -o openapi.json https://raw.githubusercontent.com/near/nearcore/master/chain/jsonrpc/openapi/openapi.json
        
    - name: Check for spec changes
      id: spec-check
      run: |
        if [ -f "openapi-cached.json" ]; then
          if ! diff -q openapi.json openapi-cached.json > /dev/null 2>&1; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Generate Swift client
      if: steps.spec-check.outputs.changed == 'true'
      run: |
        swift run generate
        cp openapi.json openapi-cached.json

    - name: Verify generated code compiles
      if: steps.spec-check.outputs.changed == 'true'
      run: |
        echo "Building NEARJSONRPCTypes package..."
        cd NEARJSONRPCTypes
        swift build
        cd ..

    - name: Run tests
      if: steps.spec-check.outputs.changed == 'true'
      env:
        SKIP_NETWORK_TESTS: "1"
      run: |
        echo "Running tests for NEARJSONRPCTypes..."
        cd NEARJSONRPCTypes
        swift test --enable-code-coverage
        cd ..
      
    - name: Generate coverage report
      if: steps.spec-check.outputs.changed == 'true'
      run: |
        PROFDATA=$(find NEARJSONRPCTypes/.build -name "default.profdata" | head -1)
        TESTBIN=$(find NEARJSONRPCTypes/.build -name "*.xctest" | head -1)
        
        if [ -n "$PROFDATA" ] && [ -n "$TESTBIN" ]; then
          if [ -f "$TESTBIN/Contents/MacOS/near-swift-clientPackageTests" ]; then
            xcrun llvm-cov export \
              "$TESTBIN/Contents/MacOS/near-swift-clientPackageTests" \
              -instr-profile "$PROFDATA" \
              -format="lcov" > coverage.lcov
          else
            # Try to find the actual test binary
            BINARY=$(find "$TESTBIN" -type f -executable | head -1)
            if [ -n "$BINARY" ]; then
              xcrun llvm-cov export \
                "$BINARY" \
                -instr-profile "$PROFDATA" \
                -format="lcov" > coverage.lcov
            fi
          fi
        else
          echo "Warning: Could not find profdata or test binary, skipping coverage report"
          touch coverage.lcov
        fi
          
    - name: Upload coverage
      if: steps.spec-check.outputs.changed == 'true'
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.lcov
        flags: unittests
        
    - name: Create Pull Request
      if: steps.spec-check.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update generated code from OpenAPI spec"
        title: "chore: update generated code from OpenAPI spec"
        body: |
          This PR updates the generated Swift code based on the latest NEAR OpenAPI specification.
          
          ## Changes
          - Updated types and client code
          - Regenerated from latest OpenAPI spec
          
          ## Testing
          - All tests passing
          - Coverage report included
          
          Please review the changes before merging.
        branch: update-generated-code
        delete-branch: true
        
  release:
    needs: generate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: google-github-actions/release-please-action@v3
      with:
        release-type: swift
        package-name: near-swift-client
        bump-minor-pre-major: true
        bump-patch-for-minor-pre-major: true